# Generated by Django 4.0.4 on 2022-06-06 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='begin_at',
            field=models.DateField(default=datetime.date(2022, 6, 2)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_at',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
        migrations.AlterUniqueTogether(
            name='pay',
            unique_together={('payroll', 'employee')},
        ),
    ]
