# Generated by Django 4.0.4 on 2022-06-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_allowance_employee_remove_deduction_employee_and_more'),
        ('payroll', '0002_alter_payroll_begin_at_alter_payroll_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='allowances',
            field=models.ManyToManyField(to='employees.employeeallowance'),
        ),
        migrations.AddField(
            model_name='pay',
            name='deductions',
            field=models.ManyToManyField(to='employees.employeededuction'),
        ),
        migrations.CreateModel(
            name='PayAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.pay')),
            ],
        ),
    ]
