# Generated by Django 4.0.4 on 2022-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('is_percent', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ManyToManyField(related_name='deductions', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('is_percent', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ManyToManyField(related_name='allowances', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
