# Generated by Django 4.0.4 on 2022-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_deduction_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='allowances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='deductions', to='employees.employee'),
        ),
    ]
