# Generated by Django 4.0.4 on 2022-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_allowance_employee_alter_deduction_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='deductions', to='employees.employee'),
        ),
    ]
