# Generated by Django 4.0.4 on 2022-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_allowance_employee_alter_deduction_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='is_percent',
            field=models.BooleanField(default=False),
        ),
    ]
